apiVersion: v1
kind: Service
metadata:
  name: db #the name that the application is looking for
  labels:
    name: db-service
    app: demo-voting-app
spec:
  type: ClusterIP #The type of service: NodePort, ClusterIP, LoadBalancer
  ports:
    - targetPort: 5432
      port: 5432 #This is the source port

  selector:  #filers
    name: postgres-app-pod #link the service to the postgres pod
    app: demo-voting-app
