apiVersion: v1
kind: Service
metadata:
  name: redis #just a name
  labels:
    name: redis-service
    app: demo-voting-app
spec:
  type: ClusterIP #The type of service: NodePort, ClusterIP, LoadBalancer
  ports:
    - targetPort: 6379
      port: 6379 #This is the source port

  selector:  #filers
    name: redis-app-pod   #link the service to the redis pod
    app: demo-voting-app
