apiVersion: v1
kind: Service
metadata:
  name: result-service #just a name
  labels:
    name: result-service
    app: demo-voting-app
spec:
  type: LoadBalancer #The type of service: NodePort, ClusterIP, LoadBalancer
  ports:
    - targetPort: 80
      port: 80 #This is the source port
  selector:  #filers
    name: result-app-pod
    app: demo-voting-app
